name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python env
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run test
        run: |
          python -m pytest